version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: meu-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - minha_rede  

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - minha_rede  
  api:
    build: 
      context: .
      dockerfile: Dockerfile      
    container_name: api
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - minha_rede  

networks:
  minha_rede:
    driver: bridge

volumes:
  redis_data:
    driver: local
