version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: meu-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data    
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis


volumes:
  redis_data:
    driver: local
